GET http://localhost:8080/gepardec-gamertrack/api/v1/matches

### (1) CREATE MATCH - Create game first
### (1) CREATE USER AND GAME BEFORE BECAUSE OF RELATIONSHIPS

POST http://localhost:8080/gepardec-gamertrack/api/v1/games
Content-Type: application/json
Accept: application/json

{
  "name": "Games",
  "rules": "Gamrules"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}


###
GET http://localhost:8080/gepardec-gamertrack/api/v1/games


### (2) Create users

POST http://localhost:8080/gepardec-gamertrack/api/v1/users
Content-Type:application/json

{
  "firstname": "User1",
  "lastname": "User1"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

###
POST http://localhost:8080/gepardec-gamertrack/api/v1/users
Content-Type:application/json

{
  "firstname": "User1",
  "lastname": "User1"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

####
GET http://localhost:8080/gepardec-gamertrack/api/v1/users



###
POST http://localhost:8080/gepardec-gamertrack/api/v1/matches
Content-Type: application/json
Accept: application/json

{
  "game": {
    "id": 1,
    "name": "Games",
    "rules": "Gamrules"
  },
  "users": [
    {
      "id": 1,
      "firstname": "NEUER NAME",
      "lastname": "Hallo"
    },
    {
      "id": 2,
      "firstname": "NEUER NAME",
      "lastname": "Hallo"
    }
  ]
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}


###
GET http://localhost:8080/gepardec-gamertrack/api/v1/matches

####

GET http://localhost:8080/gepardec-gamertrack/api/v1/matches?userId=1



###

PUT http://localhost:8080/gepardec-gamertrack/api/v1/matches/1
Content-Type: application/json
Accept: application/json

{
  "game": {
    "id": 1,
    "name": "Games2",
    "rules": "Gamrules"
  },
  "users": [
    {
      "id": 1,
      "firstname": "User1",
      "lastname": "User1"
    }
  ]
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

####

DELETE http://localhost:8080/gepardec-gamertrack/api/v1/matches/1
