GET http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes

### (1) CREATE GAMEOUTCOME - Create game first
### (1) CREATE USER AND GAME BEFORE BECAUSE OF RELATIONSHIPS

POST http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/games
Content-Type: application/json
Accept: application/json

{
  "title": "Games",
  "rules": "Gamrules"
}


###
GET http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/games


### (2) Create users

POST http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/user/new
Content-Type:application/json

{
  "firstname": "User1",
  "lastname": "User1"
}
###
POST http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/user/new
Content-Type:application/json

{
  "firstname": "User1",
  "lastname": "User1"
}
####
GET http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/user/list



###
POST http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes
Content-Type: application/json
Accept: application/json

{
  "gameId": 1,
  "userIds": [1,2]
}


###
GET http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes

####

GET http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes?userId=1



###

PUT http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes/1
Content-Type: application/json
Accept: application/json

{
  "gameId": 1,
  "id": 1,
  "userIds": [
    1
  ]
}

####

###DELETE http://localhost:8080/gamertrack-application-1.0-SNAPSHOT/api/v1/gameoutcomes/1
