GET http://localhost:8080/gamertrack-war-1.0-SNAPSHOT/api/v1/games


###

POST http://localhost:8080/gamertrack-war-1.0-SNAPSHOT/api/v1/games
Content-Type: application/json
Accept: application/json

{
  "title": "TestNamRTeste2",
  "rules": "TestRules"
}

###
GET http://localhost:8080/gamertrack-war-1.0-SNAPSHOT/api/v1/games/1
Accept: application/json

###

DELETE http://localhost:8080/gamertrack-war-1.0-SNAPSHOT/api/v1/games/1

###
PUT http://localhost:8080/gamertrack-war-1.0-SNAPSHOT/api/v1/games/1
Content-Type: application/json
Accept: application/json

{
  "title": "UpdatedTitle",
  "rules": "New Rules"
}
