GET http://localhost:8080/gepardec-gamertrack/api/v1/games

###

POST http://localhost:8080/gepardec-gamertrack/api/v1/games
Accept: application/json
Content-Type: application/json

{
  "name": "Gamese",
  "rules": "Gamrules"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

###
GET http://localhost:8080/gepardec-gamertrack/api/v1/games/KdAML2npimzqsgHf
Accept: application/json

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

###

DELETE http://localhost:8080/gepardec-gamertrack/api/v1/games/dvNgfgoQ2GbKhQ5X

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

###

POST http://localhost:8080/gepardec-gamertrack/api/v1/games
Accept: application/json
Content-Type: application/json

{
  "name": "Games",
  "rules": "Gamrules"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 201, "Response status is not 201");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}

###
PUT http://localhost:8080/gepardec-gamertrack/api/v1/games/KdAML2npimzqsgHf
Content-Type: application/json
Accept: application/json

{
  "name": "UpdatedTitle",
  "rules": "New Rules"
}
> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Response content-type is json", function () {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json",
        "Expected 'application/json' but received '" + type + "'");
  });
%}